### ISSUE TITLE
Flipping Broken for non-0 resolution levels

### ISSUE THREAD

**Issue by kkoz** [glencoesoftware/omero-ms-image-region#105]
Any attempt to use the `flip` query parameter when requesting a tile at a resolution level > 0 results in the following exception:
```java.lang.RuntimeException: Invalid Region, the width must be positive:0
	at omeis.providers.re.RenderingStrategy.isRegionValid(RenderingStrategy.java:92)
	at omeis.providers.re.RenderingStrategy.initAxesSize(RenderingStrategy.java:118)
	at omeis.providers.re.HSBStrategy.getPlaneDimsAsString(HSBStrategy.java:380)
	at omeis.providers.re.Renderer.getPlaneDimsAsString(Renderer.java:614)
	at omeis.providers.re.RenderingStats.getStats(RenderingStats.java:199)
	at com.glencoesoftware.omero.ms.image.region.ImageRegionRequestHandler.render(ImageRegionRequestHandler.java:561)
	at com.glencoesoftware.omero.ms.image.region.ImageRegionRequestHandler.getRegion(ImageRegionRequestHandler.java:347)
	at com.glencoesoftware.omero.ms.image.region.ImageRegionRequestHandler.renderImageRegion(ImageRegionRequestHandler.java:322)
	at com.glencoesoftware.omero.ms.core.OmeroRequest.execute(OmeroRequest.java:109)
	at com.glencoesoftware.omero.ms.image.region.ImageRegionVerticle.renderImageRegion(ImageRegionVerticle.java:180)
	at com.glencoesoftware.omero.ms.image.region.ImageRegionVerticle.lambda$0(ImageRegionVerticle.java:128)
	at io.vertx.core.eventbus.impl.HandlerRegistration.deliver(HandlerRegistration.java:271)
	at io.vertx.core.eventbus.impl.HandlerRegistration.handle(HandlerRegistration.java:249)
	at io.vertx.core.eventbus.impl.EventBusImpl$InboundDeliveryContext.next(EventBusImpl.java:573)
	at io.vertx.core.eventbus.impl.EventBusImpl.lambda$deliverToHandler$5(EventBusImpl.java:532)
	at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:369)
	at io.vertx.core.impl.WorkerContext.lambda$wrapTask$0(WorkerContext.java:35)
	at io.vertx.core.impl.TaskQueue.run(TaskQueue.java:76)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)```

This appears to be caused by the flipping calculation always being applied at the full image size. This results in start positions way out of the image bounds, causing this error.

**Comment by kkoz** [comment]
Fixed by #104
